# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: my-custom-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push the Docker image
        env:
          REGISTRY: clibequilibrium
          REPOSITORY: sample
        run: |
          # Build a docker container and push it to ECR
          git_hash=$(git rev-parse --short HEAD)
          docker build -t $REGISTRY/$REPOSITORY:$git_hash .
          echo "Pushing image to DockerHub..."
          echo "repo name: $REGISTRY/$REPOSITORY:$git_hash"
          docker push $REGISTRY/$REPOSITORY:$git_hash
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$git_hash"
